apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: nginx
    app.kubernetes.io/instance: webserver
    app.kubernetes.io/part-of: wordpress
    app.openshift.io/runtime: nginx
  name: wordpress
  namespace: default
spec:
  template:
    metadata:
      labels:
        net-tcp-8080: server
        net-tcp-9000: client
    spec:
      containers:
      - name: wordpress-core
        image: wordpress-wordpress-run
        env:
        - name: WORDPRESS_DB_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: wordpress-config
        - name: WORDPRESS_DB_NAME
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: wordpress-config
        envFrom:
        - configMapRef:
            name: wordpress-config
        imagePullPolicy: Always
        ports:
        - containerPort: 9000
          name: 9000-tcp
          protocol: TCP
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: wordpress-htdocs
          mountPath: /var/www/html
        - name: php-fpm-secrets-volume
          mountPath: /run/secrets/wordpress
          readOnly: true
        - name: mariadb-secrets-volume
          mountPath: /run/secrets/WORDPRESS_DB_PASSWORD
          readOnly: true
          subPath: MYSQL_PASSWORD
        - name: wordpress-volume
          mountPath: /var/www/html/wp-content/
          subPath: dev/wp-content
        - name: plugins-themes
          mountPath: /var/www/html/wp-content/
          subPath: plugins
          readOnly: true
      - name: wordpress-nginx
        image: wordpress-nginx-run
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
          name: 8080-tcp
          protocol: TCP
        resources:
          limits:
            cpu: 400m
            memory: 500Mi
          requests:
            cpu: 100m
            memory: 250Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - name: wordpress-htdocs
          mountPath: /var/www/html
        - name: wordpress-volume
          mountPath: /var/www/html/wp-content/
          subPath: dev/wp-content
        - name: nginx-configmap-volume
          mountPath: /etc/nginx/conf.d/nginx.conf
          subPath: nginx.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: nginx.conf
            path: nginx.conf
          name: wordpress-config
        name: nginx-configmap-volume
      - emptyDir: {}
        name: wordpress-htdocs
      - name: wordpress-volume
        persistentVolumeClaim:
          claimName: wordpress
      - name: plugins-themes
        persistentVolumeClaim:
          claimName: plugins-themes
      - name: php-fpm-secrets-volume
        secret:
          defaultMode: 420
          secretName: wordpress-secrets
      - name: mariadb-secrets-volume
        secret:
          defaultMode: 420
          items:
          - key: MYSQL_PASSWORD
            path: MYSQL_PASSWORD
          secretName: wordpress-secrets

