apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- allow-from-openshift-ingress.yaml
- allow-tcp-port-3306.yaml
- allow-tcp-port-9000.yaml

commonLabels:
  role: networking
  name: wordpress-networking


