kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: wordpress-mariadb-backup-volume-verification
  annotations:
    openshift.io/display-name:  Backup volume verification.
    description: Backup volume templates for verification.
    tags: backups,wordpress

parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "backup-verification"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "23576a"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: POOL_NAME
    displayName: "Pool name"
    description: "The database shared pool instance."
    required: true
    value: "pool"

objects:
  - kind: PersistentVolumeClaim
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      labels:
        app: ${APP_NAME}-${ROLE_NAME}
        env: ${ENV_NAME}
        name: ${APP_NAME}-${ROLE_NAME}
        role: verification-backup-container-db
    spec:
      accessModes:
        - ReadWriteOnce
      resources:
        requests:
          storage: 500M
      storageClassName: netapp-file-standard
      volumeMode: Filesystem
