kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: mariadb-run
  annotations:
    description: Keeps track of wordpress-mariadb-run images
  labels:
    name: wordpress-mariadb-run-image

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wordpress-mariadb-run
  annotations:
    description: This builds the wordpress-mariadb-run image from GIT source.

spec:
  strategy:
    dockerStrategy:
      from:
          kind: DockerImage
          name: alpine:3.20.3
      type: Docker
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  runPolicy: Serial
  source:
    type: Git
    git:
      ref: main
      uri: https://github.com/bcgov/wordpress.git
    contextDir: openshift/templates/images/mariadb/docker
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-mariadb-run:dev
