kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: wordpress-nginx-run
  annotations:
    description: Keeps track of wordpress-nginx-run images
  labels:
    name: wordpress-nginx-run-images
---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wordpress-nginx-run

spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  runPolicy: Serial
  source:
    type: Git
    git:
      ref: feature/descw-3022-update-dependency-WP-WPCLI-NGINX
      uri: https://github.com/bcgov/wordpress.git
    contextDir: openshift/templates/images/nginx/docker
  strategy:
    dockerStrategy:
      from:
          kind: DockerImage
          name: nginx:1.27.5
      type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-nginx-run:dev

