kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: wordpress-sidecar-run
  annotations:
    description: Keeps track of changes to the sidecar runtime deploy image
  labels:
    name: wordpress-sidecar-run
spec:
  lookupPolicy:
    local: true

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wordpress-sidecar-run
  annotations:
    description: Builds sidecar final image.
  labels:
    name: wordpress-sidecar-run
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  source:
    type: Git
    git:
      ref: feature/descw-3022-update-dependency-WP-WPCLI-NGINX
      uri: https://github.com/bcgov/wordpress.git
    contextDir: openshift/templates/images/sidecar/docker
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: ubuntu:22.04
      buildArgs:
        - name: CHANGE_USER
          value: '1003760000'
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-sidecar-run:dev
  resources:
    limits:
      cpu: 1
      memory: 3Gi
