kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: wordpress-wordpress-run
  annotations:
    description: Keeps track of base WordPress core images
  labels:
    name: wordpress-wordpress-run-images
spec:
  lookupPolicy:
    local: true

---
kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: wordpress-wordpress-run
  labels:
    name: wordpress-wordpress-run
spec:
  successfulBuildsHistoryLimit: 2
  failedBuildsHistoryLimit: 2
  runPolicy: Serial
  completionDeadlineSeconds: 1800
  strategy:
    dockerStrategy:
      from:
        kind: DockerImage
        name: wordpress:6.6.2-php8.3-fpm-alpine
    type: Docker
  source:
    type: Git
    git:
      ref: main
      uri: https://github.com/bcgov/wordpress.git
    contextDir: openshift/templates/images/wordpress/docker
  output:
    to:
      kind: ImageStreamTag
      name: wordpress-wordpress-run:dev
  resources:
    limits:
      cpu: 1
      memory: 3Gi