kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: ubuntu
  annotations:
    description: Keeps track of ubuntu images that originate from DockerHub
  labels:
    source: docker-remote
    name: ubuntu-image
spec:
  tags:
    - name: "22.04"
      from:
        kind: DockerImage
        name: "artifacts.developer.gov.bc.ca/docker-remote/ubuntu:22.04"
      referencePolicy:
        type: Local