kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: wordpress
  annotations:
    description: Keeps track of WordPress images that originate from DockerHub
  labels:
    name: wordpress-image
    source: docker-remote
spec:
  tags:
    - name: "6.3.0-php8.0-fpm-alpine"
      from:
        kind: DockerImage
        name: "artifacts.developer.gov.bc.ca/docker-remote/wordpress:6.2.0-php8.0-fpm-alpine"
      referencePolicy:
        type: Local
