kind: ImageStream
apiVersion: image.openshift.io/v1
metadata:
  name: wordpress-php-fpm
  annotations:
    description: Keeps track of WordPress images that originate from DockerHub
  labels:
    name: wordpress-image
    source: docker-remote
spec:
  tags:
    - name: "wordpress:6.1.1-php7.4-fpm-alpine"
      from:
        kind: DockerImage
        name: "artifacts.developer.gov.bc.ca/docker-remote/wordpress:6.1.1-php7.4-fpm-alpine"
      referencePolicy:
        type: Local