kind: Template
apiVersion: v1
metadata:
  name: wordpress-php-fpm-image-stream
  annotations:
    openshift.io/display-name: WordPress php-fpm Image
    description: ImageStream definitions for WordPress fpm on alpine and bullseye that originate from Dockerhub
parameters:
  - name: IMAGE_NAME
    displayName: "The name of this image"
    required: true
    value: "wordpress-php-fpm"
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "wordpress-php-fpm"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "23576a"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "tools"
  - name: IMAGE_TAG
    displayName: "The WordPress image tag"
    description: "This is the official image tag, which is later used to build the wordpress-wordpress-run"
    value: "6.1.1-php7.4-fpm-alpine"

objects:
  - kind: ImageStream
    apiVersion: v1
    metadata:
      name: ${IMAGE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: Keeps track of php 7.4 images that originate from Dockerhub
      labels:
        name: dockerhub-${ROLE_NAME}
        app: ${APP_NAME}
        role: ${ROLE_NAME}
        env: ${ENV_NAME}
        source: dockerhub
    spec:
      tags:
        - name: "wordpress:${IMAGE_TAG}"
          from:
            kind: DockerImage
            name: "docker-remote.artifacts.developer.gov.bc.ca/wordpress:${IMAGE_TAG}"
          referencePolicy:
            type: Local
