apiVersion: apps/v1
kind: Pod
metadata:
  labels:
    app.kubernetes.io/part-of: wordpress
  name: wordpress-plugins-themes
  namespace: default
spec:
  replicas: 1
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        name: wordpress-plugins-themes
        net-tcp-3306: client
    spec:
      containers:
      - name: wordpress-plugins-themes
        image: wordpress-plugins-themes-run
        env:
        envFrom:
        - configMapRef:
            name: wordpress-config
        imagePullPolicy: Always
        restartPolicy: Never
        securityContext:
        volumeMounts:
        - name: plugins-themes
          mountPath: /var/www/html/wp-content/
          subPath: dev/wp-content
      volumes:
      - name: plugins-themes
        persistentVolumeClaim:
          claimName: wordpress
