apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app.kubernetes.io/part-of: wordpress
  name: wordpress-plugins-themes
  namespace: default
spec:
  ttlSecondsAfterFinished: 120
  strategy: 
    type: Recreate
  template:
    metadata:
      labels:
        name: wordpress-plugins-themes
        net-tcp-3306: client
    spec:
      containers:
      - name: wordpress-plugins-themes
        image: wordpress-plugins-themes-run
        env:
        envFrom:
        - configMapRef:
            name: wordpress-config
        imagePullPolicy: Always
        securityContext:
        volumeMounts:
        - name: plugins
          mountPath: /var/www/html/wp-content/plugins
        - name: themes
          mountPath: /var/www/html/wp-content/themes
      volumes:
      - name: plugins
        persistentVolumeClaim:
          claimName: plugins
      - name: themes
        persistentVolumeClaim:
        claimName: themes
      restartPolicy: Never
