apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- job.yaml
- volumes.yaml

commonLabels:
  role: plugins-themes
  name: wordpress-plugins-themes

# Creates the configmaps which automatically get version controlled via hashes.
configMapGenerator:
- name: wordpress-plugins-themes-config
  files:
  - composer.json
  