apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins-themes
  namespace: default
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500M