# NB: This file is not currently being used anywhere - see deployments/kustomize/base/plugins_themes/kustomization.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins-themes
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500M
