apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: plugins
  namespace: default
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500M
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: themes
  namespace: default
spec:
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 500M
