kind: Template
apiVersion: template.openshift.io/v1
metadata:
  name: wordpress-php-fpm-ps-secrets
  annotations:
    openshift.io/display-name:  Secrets templates for the persistent storage (classic) version of the WordPress deploy.
    description: Secrets templates for the persistent storage (classic) version of the WordPress deploy.
    tags: php-fpm,wordpress

parameters:
  - name: APP_NAME
    displayName: "App Name"
    description: "The name of the application (grouped)."
    required: true
    value: "wordpress"
  - name: ROLE_NAME
    displayName: "Component Name"
    description: "The name of the application role."
    required: true
    value: "php-fpm"
  - name: PROJECT_NAMESPACE
    displayName: "OpenShift Project Namespace"
    description: "The namespace of the OpenShift project containing the application."
    required: true
    value: "23576a"
  - name: ENV_NAME
    displayName: "Environment name"
    description: "The name for this environment [dev, test, prod, tools]"
    required: true
    value: "dev"
  - name: SITE_NAME
    displayName: "Site name"
    description: "The name for the site (a-zA-Z_)"
    required: true
    value: "global"

  - name: WORDPRESS_NONCE_SALT
    displayName: "WORDPRESS_NONCE_SALT"
    description: "Unique nonce salt."
    generate: expression
    from: "[a-zA-Z0-9]{42}"
  - name: WORDPRESS_AUTH_KEY
    displayName: "WORDPRESS_AUTH_KEY"
    description: "WORDPRESS_AUTH_KEY"
    generate: expression
    from: "[a-zA-Z0-9]{42}"
  - name: WORDPRESS_SECURE_AUTH_KEY
    displayName: "WORDPRESS_SECURE_AUTH_KEY"
    description: "WORDPRESS_SECURE_AUTH_KEY"
    generate: expression
    from: "[a-zA-Z0-9]{42}"
  - name: WORDPRESS_LOGGED_IN_KEY
    displayName: "WORDPRESS_LOGGED_IN_KEY"
    description: "WORDPRESS_LOGGED_IN_KEY"
    generate: expression
    from: "[a-zA-Z0-9]{42}"
  - name: WORDPRESS_NONCE_KEY
    displayName: "WORDPRESS_NONCE_KEY"
    description: "WORDPRESS_NONCE_KEY"
    generate: expression
    from: "[a-zA-Z0-9]{42}"
  - name: WORDPRESS_AUTH_SALT
    displayName: "WORDPRESS_AUTH_SALT"
    description: "WORDPRESS_AUTH_SALT"
    generate: expression
    from: "[a-zA-Z0-9]{42}"
  - name: WORDPRESS_SECURE_AUTH_SALT
    displayName: "WORDPRESS_SECURE_AUTH_SALT"
    description: "WORDPRESS_SECURE_AUTH_SALT"
    generate: expression
    from: "[a-zA-Z0-9]{42}"
  - name: WORDPRESS_LOGGED_IN_SALT
    displayName: "WORDPRESS_LOGGED_IN_SALT"
    description: "WORDPRESS_LOGGED_IN_SALT"
    generate: expression
    from: "[a-zA-Z0-9]{42}"

objects:
  - kind: Secret
    apiVersion: v1
    metadata:
      name: ${APP_NAME}-${ROLE_NAME}-secrets--${SITE_NAME}
      namespace: ${PROJECT_NAMESPACE}-${ENV_NAME}
      annotations:
        description: "wordpress secrets"
      labels:
        name: ${APP_NAME}-${ROLE_NAME}-secrets--${SITE_NAME}
        app: ${APP_NAME}
        env: ${ENV_NAME}
        site: ${SITE_NAME}
    type: Opaque
    stringData:
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      WORDPRESS_SECURE_AUTH_KEY: ${WORDPRESS_SECURE_AUTH_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_AUTH_SALT: ${WORDPRESS_AUTH_SALT}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}
