name: Build MariaDB Image.
on:
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/mariadb/**/*"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  deploy:
    if: github.repository_owner == 'bcgov'
    runs-on: ubuntu-latest
    steps:
      - name: Install oc
        if: "runner.os != 'Linux'"
        uses: redhat-actions/openshift-tools-installer@v1
        with:
          oc: latest

      - name: Authenticate and set context
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OpenShiftServerURL }}
          openshift_token: ${{ secrets.OpenShiftToken }}
          namespace: ${{ secrets.OPENSHIFT_LICENSEPLATE }}-tools

      - name: Image build
        run: |
          oc start-build wordpress-mariadb-run --follow
