name: Build MariaDB Image.
on:
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/mariadb/**/*"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  deploy:
    if: github.repository_owner == 'bcgov'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install and set up oc
        uses: bcgov/wordpress/.github/workflows/oc-setup.yaml@feature/descw-1065-update-openshift-actions-node-16

      - name: Image build
        run: |
          oc start-build wordpress-mariadb-run --follow
