name: Build MariaDB Image.
on:
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/mariadb/**/*"
  workflow_dispatch:
defaults:
  run:
    working-directory: ./
jobs:
  oc:
    uses: bcgov/wordpress/.github/workflows/oc-build-image.yaml@main
    with:
      image: wordpress-mariadb-run
    secrets:
      openshift_server_url: ${{ secrets.OpenShiftServerURL }}
      openshift_token: ${{ secrets.OpenShiftToken }}
      openshift_licenseplate: ${{ secrets.OPENSHIFT_LICENSEPLATE }}
