name: Build Nginx Image
permissions:
  contents: read # Used to checkout/read this repository's contents
  id-token: write # Used by redhat-actions/oc-login in oc-build-image.yaml
  actions: read # Used to call the reusable workflow oc-build-image.yaml
on:
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/nginx/**/*"
  workflow_dispatch: # Allows manual triggering of the workflow
defaults:
  run:
    working-directory: ./
jobs:
  oc:
    uses: bcgov/wordpress/.github/workflows/oc-build-image.yaml@feature/DESCW-3086_workflow-permissions
    with:
      image: wordpress-nginx-run
    secrets:
      openshift_server_url: ${{ secrets.OpenShiftServerURL }}
      openshift_token: ${{ secrets.OpenShiftToken }}
      openshift_licenseplate: ${{ secrets.OPENSHIFT_LICENSEPLATE }}
