name: Build Sidecar Utility Image.
on:
  push:
    branches:
      - main
    paths:
      - "openshift/templates/images/sidecar/**/*"
  workflow_dispatch: # Allows manual triggering of the workflow
defaults:
  run:
    working-directory: ./
jobs:
  oc:
    uses: bcgov/wordpress/.github/workflows/oc-build-image.yaml@feature/DESCW-3086_workflow-permissions
    with:
      image: wordpress-sidecar-run
    secrets:
      openshift_server_url: ${{ secrets.OpenShiftServerURL }}
      openshift_token: ${{ secrets.OpenShiftToken }}
      openshift_licenseplate: ${{ secrets.OPENSHIFT_LICENSEPLATE }}
