apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
- routes.yaml
- networking

commonLabels:
  app: wordpress
  env: dev
configMapGenerator:
- name: wordpress-config
  behavior: merge
  literals:
  - MYSQL_DATABASE=dev
  - WORDPRESS_DB_HOST=wordpress-mariadb
  - MYSQL_USER=dev_user
  - APP_DOMAIN=example.gov.bc.ca
patchesStrategicMerge:
- patch.yaml